
package com.web_final_task.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import static com.web_final_task.config.ConfigManager.applicationConfig;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UsersPortService", targetNamespace = "http://gridu.qa.payment.griddynamics.com/springsoap/gen", wsdlLocation = "http://localhost:8089/ws/users.wsdl")
public class UsersPortService extends Service {

    private final static URL USERSPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERSPORTSERVICE_EXCEPTION;
    private final static QName USERSPORTSERVICE_QNAME = new QName("http://gridu.qa.payment.griddynamics.com/springsoap/gen", "UsersPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(applicationConfig().getUserManagementUrl());
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERSPORTSERVICE_WSDL_LOCATION = url;
        USERSPORTSERVICE_EXCEPTION = e;
    }

    public UsersPortService() {
        super(__getWsdlLocation(), USERSPORTSERVICE_QNAME);
    }

    public UsersPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERSPORTSERVICE_QNAME, features);
    }

    public UsersPortService(URL wsdlLocation) {
        super(wsdlLocation, USERSPORTSERVICE_QNAME);
    }

    public UsersPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERSPORTSERVICE_QNAME, features);
    }

    public UsersPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsersPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UsersPort
     */
    @WebEndpoint(name = "UsersPortSoap11")
    public UsersPort getUsersPortSoap11() {
        return super.getPort(new QName("http://gridu.qa.payment.griddynamics.com/springsoap/gen", "UsersPortSoap11"), UsersPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsersPort
     */
    @WebEndpoint(name = "UsersPortSoap11")
    public UsersPort getUsersPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://gridu.qa.payment.griddynamics.com/springsoap/gen", "UsersPortSoap11"), UsersPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERSPORTSERVICE_EXCEPTION!= null) {
            throw USERSPORTSERVICE_EXCEPTION;
        }
        return USERSPORTSERVICE_WSDL_LOCATION;
    }

}
