
package com.web_final_task.service;

import com.web_final_task.entity.xml.CreateUserRequest;
import com.web_final_task.entity.xml.CreateUserResponse;
import com.web_final_task.entity.xml.DeleteUserRequest;
import com.web_final_task.entity.xml.DeleteUserResponse;
import com.web_final_task.entity.xml.GetUserDetailsRequest;
import com.web_final_task.entity.xml.GetUserDetailsResponse;
import com.web_final_task.entity.xml.ObjectFactory;
import com.web_final_task.entity.xml.UpdateUserRequest;
import com.web_final_task.entity.xml.UpdateUserResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UsersPort", targetNamespace = "http://gridu.qa.payment.griddynamics.com/springsoap/gen")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsersPort {


    /**
     * 
     * @param updateUserRequest
     * @return
     *     returns com.web_final_task.entity.xml.UpdateUserResponse
     */
    @WebMethod
    @WebResult(name = "updateUserResponse", targetNamespace = "http://gridu.qa.payment.griddynamics.com/springsoap/gen", partName = "updateUserResponse")
    public UpdateUserResponse updateUser(
        @WebParam(name = "updateUserRequest", targetNamespace = "http://gridu.qa.payment.griddynamics.com/springsoap/gen", partName = "updateUserRequest")
                UpdateUserRequest updateUserRequest);

    /**
     * 
     * @param deleteUserRequest
     * @return
     *     returns com.web_final_task.entity.xml.DeleteUserResponse
     */
    @WebMethod
    @WebResult(name = "deleteUserResponse", targetNamespace = "http://gridu.qa.payment.griddynamics.com/springsoap/gen", partName = "deleteUserResponse")
    public DeleteUserResponse deleteUser(
        @WebParam(name = "deleteUserRequest", targetNamespace = "http://gridu.qa.payment.griddynamics.com/springsoap/gen", partName = "deleteUserRequest")
                DeleteUserRequest deleteUserRequest);

    /**
     * 
     * @param getUserDetailsRequest
     * @return
     *     returns com.web_final_task.entity.xml.GetUserDetailsResponse
     */
    @WebMethod
    @WebResult(name = "getUserDetailsResponse", targetNamespace = "http://gridu.qa.payment.griddynamics.com/springsoap/gen", partName = "getUserDetailsResponse")
    public GetUserDetailsResponse getUserDetails(
        @WebParam(name = "getUserDetailsRequest", targetNamespace = "http://gridu.qa.payment.griddynamics.com/springsoap/gen", partName = "getUserDetailsRequest")
                GetUserDetailsRequest getUserDetailsRequest);

    /**
     * 
     * @param createUserRequest
     * @return
     *     returns com.web_final_task.entity.xml.CreateUserResponse
     */
    @WebMethod
    @WebResult(name = "createUserResponse", targetNamespace = "http://gridu.qa.payment.griddynamics.com/springsoap/gen", partName = "createUserResponse")
    public CreateUserResponse createUser(
        @WebParam(name = "createUserRequest", targetNamespace = "http://gridu.qa.payment.griddynamics.com/springsoap/gen", partName = "createUserRequest")
                CreateUserRequest createUserRequest);

}
